apiVersion: harness.io/v1
kind: Workflow
name: EDA_Airflow_IDMC_Deployment_Only
identifier: EDA_Airflow_IDMC_Deployment_Only
type: service
owner: user:account/vivek.sharma@takeda.com
projectIdentifier: EDA
orgIdentifier: GDDT
metadata: {}
spec:
  output:
    resultLink: "${{ steps.execute-pipeline.output.resultLink }}"
  parameters:
    - title: Airflow_IDMC
      required:
        - Platform
      properties:
        Platform:
          type: array
          title: Select Platform(s)
          ui:widget: checkboxes
          ui:options:
            inline: true
          description: Select one or more platforms to trigger
          items:
            type: string
            enum:
              - Airflow
              - IDMC
          uniqueItems: true
      dependencies:
        Platform:
          oneOf:
            # Case 1: Airflow selected
            - required:
                - Platform
                - airflowSpecificField
              properties:
                Platform:
                  contains:
                    enum:
                      - Airflow
                airflowSpecificField:
                  title: Airflow Specific Option
                  type: string
                  description: Airflow specific configuration option
                  ui:widget: radio
                  enum:
                    - Option1
                    - Option2

            # Case 2: IDMC selected
            - required:
                - Platform
                - idmcSpecificField
              properties:
                Platform:
                  contains:
                    enum:
                      - IDMC
                idmcSpecificField:
                  title: IDMC Specific Option
                  type: string
                  description: IDMC specific configuration option
                  ui:widget: radio
                  enum:
                    - OptionA
                    - OptionB

            # Case 3: Both Airflow + IDMC selected
            - required:
                - Platform
                - airflowSpecificField
                - idmcSpecificField
              properties:
                Platform:
                  contains:
                    enum:
                      - Airflow
                      - IDMC
                airflowSpecificField:
                  title: Airflow Specific Option
                  type: string
                  description: Airflow specific configuration option
                  ui:widget: radio
                  enum:
                    - Option1
                    - Option2
                idmcSpecificField:
                  title: IDMC Specific Option
                  type: string
                  description: IDMC specific configuration option
                  ui:widget: radio
                  enum:
                    - OptionA
                    - OptionB

  steps:
    - id: execute-pipeline
      name: Execute Harness Pipeline
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/etUzqvIyRSixpOWJqF4_Qg/all/orgs/GDDT/projects/EDA/pipelines/Demo_Airflow_CICD_Automation/pipeline-studio/?storeType=INLINE
        inputset:
          Platform: "${{ parameters.Platform.join(',') }}"
          airflowSpecificField: "${{ parameters.airflowSpecificField }}"
          idmcSpecificField: "${{ parameters.idmcSpecificField }}"
        apikey: "${{ parameters.token }}"
