apiVersion: harness.io/v1
kind: Workflow
name: Pipeline_Switcher
identifier: pipeline_switcher
type: service
owner: user:account/you@takeda.com
projectIdentifier: EDA
orgIdentifier: GDDT
metadata: {}
spec:
  parameters:
    - title: Pipeline Choice
      required:
        - pipelineChoice
        - token
      properties:
        pipelineChoice:
          title: Which pipeline do you want to run?
          type: string
          ui:widget: radio
          enum:
            - Airflow
            - IDMC
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
          description: Harness API key to authenticate the trigger action
  steps:
    # Step 1: Run Airflow pipeline only if user picked Airflow
    - id: run-airflow
      name: Run Airflow Pipeline
      when:
        condition: "<+parameters.pipelineChoice> == 'Airflow'"
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/etUzqvIyRSixpOWJqF4_Qg/all/orgs/GDDT/projects/EDA/pipelines/IDP_PIPELINE_2_Clone/pipeline-studio/?storeType=INLINE
        inputset:
          # pass any other parameters if needed
        apikey: "${{ parameters.token }}"

    # Step 2: Run IDMC pipeline only if user picked IDMC
    - id: run-idmc
      name: Run IDMC Pipeline
      when:
        condition: "<+parameters.pipelineChoice> == 'IDMC'"
      action: trigger:harness-custom-pipeline
      input:
        url:https://app.harness.io/ng/account/etUzqvIyRSixpOWJqF4_Qg/all/orgs/GDDT/projects/EDA/pipelines/IDP_PIPELINE_1/pipeline-studio/?storeType=INLINE
        inputset:
          # pass any other parameters if needed
        apikey: "${{ parameters.token }}"
