apiVersion: harness.io/v1
kind: Workflow
name: EDA_Airflow_IDMC_Deployment_Only
identifier: EDA_Airflow_IDMC_Deployment_Only_4
type: service
owner: user:account/vivek.sharma@takeda.com
projectIdentifier: EDA
orgIdentifier: GDDT
metadata: {}
spec:
  parameters:
    - title: Basic Info
      required:
        - requesterName
        - requesterEmail
        - token
        - edbId
        - environment
      properties:
        requesterName:
          title: Your Name
          type: string
          description: Your Full name
        requesterEmail:
          title: Your Email
          type: string
          description: Your Takeda Email address
          pattern: "^[a-zA-Z0-9._%+-]+@[tT][aA][kK][eE][dD][aA]\\.com$"
          patternErrorMessage: "Please enter a valid Takeda email address"
        businessOwnerEmail:
          title: Business Owner Email
          type: string
          description: Enter the Takeda Email address
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
          description: Harness API key to authenticate the trigger action
        region:
          title: Region
          type: string
          description: Select the cloud region
          enum: [US, JP, EU]
        environment:
          title: Migration Environment
          type: string
          description: Select the source and target environment for the migration
          ui:widget: radio
          enum:
            - Dev to Test
            - Test to Prod
        Configuration Item:
          title: Configuration Item
          type: string
          description: Enter the Configuration Item
    - title: Airflow Basic Migration Details
      required:
        - enableAirflowMigration
      properties:
        enableAirflowMigration:
          title: Enable Airflow Migration?
          type: string
          ui:widget: radio
          enum:
            - "Yes"
            - "No"
          default: "No"
      dependencies:
        enableAirflowMigration:
          oneOf:
            - properties:
                enableAirflowMigration:
                  enum: ["No"]
            - required:
                - updateCreateConnection
                - updateCreateVariable
                - fullMigration
                - edbId
              properties:
                enableAirflowMigration:
                  enum: ["Yes"]
                gitRepository:
                  title: Git Repository URL
                  type: string
                  description: Enter the Git repository URL where your code resides.
                  ui:placeholder: "https://github.com/org/repo.git"
                updateCreateConnection:
                  title: Update/Create Connection
                  type: string
                  description: It'll fetch the connection details from the vault folder\\connections. Make sure you have added/updated the connection.
                  ui:widget: radio
                  enum: ["Yes", "No"]
                  default: "Yes"
                updateCreateVariable:
                  title: Update/Create Variable
                  type: string
                  description: It'll fetch the variables details from the vault folder\\variables. Make sure you have added/updated the variables.
                  ui:widget: radio
                  enum: ["Yes", "No"]
                  default: "Yes"
                edbId:
                  title: EDB ID
                  type: string
                  description: Your EDB ID (numbers only)
                  pattern: "^\\d+$"  
                fullMigration:
                  title: Full Migration
                  type: string
                  description: Select 'Yes' for full migration. This will migrate your DAG folder, plugins folder and requirement.txt and automatically update the version in MWAA.
                  ui:widget: radio
                  enum: ['Yes','No']
                  default: 'Yes'
        fullMigration:
          oneOf:
            - properties:
                fullMigration:
                  enum: ['Yes']
            - required:
                - migrationComponents
              properties:
                fullMigration:
                  enum: ['No']
                migrationComponents:
                  type: array
                  title: Select Components to Migrate
                  ui:widget: checkboxes
                  ui:options:
                    inline: true
                  items:
                    type: string
                    enum: [DAGs, Plugins, Requirements]
                  uniqueItems: true
        migrationComponents:
          oneOf:
            - required:
                - dagFileNames
              properties:
                migrationComponents:
                  contains:
                    enum: [DAGs]
                dagFileNames:
                  title: DAG File Names
                  type: string
                  description: Enter the DAG file names you want to migrate (comma-separated like dag1.py, dag2.py). Note - File names should be exactly the same as mentioned in S3
                  ui:placeholder: dag1.py, dag2.py, dag3.py

    - title: IDMC Migration Details
      required:
        - enableMigrationDetails
      properties:
        enableMigrationDetails:
          title: Enable Migration Details?
          type: string
          ui:widget: radio
          enum:
            - "Yes"
            - "No"
          default: "No"
      dependencies:
        enableMigrationDetails:
          oneOf:
            - properties:
                enableMigrationDetails:
                  enum: ["No"]
            - required:
                - projectName
              properties:
                enableMigrationDetails:
                  enum: ["Yes"]
                projectName:
                  title: Project Name
                  type: string
                  description: The name of the Projet to be migrated
                performS3Migration:
                  title: Do you want to migrate Server Side Components?
                  type: string
                  description: Select 'Yes' to include the Server Side Components in the migration.
                  ui:widget: radio
                  enum: ["No","Yes"]
                migrationType:
                  title: Migration Type
                  type: string
                  description: Choose whether to migrate the entire project or only specific assets.
                  ui:widget: radio
                  default: Full Migration
                  enum: [Full Migration, Selective Migration]
        migrationType:
          oneOf:
            - properties:
                migrationType:
                  enum: [Full Migration]
            - properties:
                migrationType:
                  enum: [Selective Migration]
                selectiveAssets:
                  title: Selective Assets
                  type: array
                  description: Enter the asset names to migrate. You can enter multiple assets.
                  items:
                    type: string
                    title: Asset Name

  steps:
    - id: execute-pipeline
      name: Execute Harness Pipeline
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/etUzqvIyRSixpOWJqF4_Qg/all/orgs/GDDT/projects/EDA/pipelines/Testing_CI_CD/pipeline-studio/?storeType=INLINE
        inputset:
          requesterName: "${{ parameters.requesterName }}"
          requesterEmail: "${{ parameters.requesterEmail }}"
          edb_id: "${{ parameters.edbId }}"
          environment: "${{ parameters.environment }}"
          fullMigration: "${{ parameters.fullMigration }}"
          updateCreateConnection: "${{ parameters.updateCreateConnection }}"
          updateCreateVariable: "${{ parameters.updateCreateVariable }}"
          migrationComponents: "${{ parameters.migrationComponents.join(',') }}"
          dagFileNames: "${{ parameters.dagFileNames }}"
          gitRepository: "${{ parameters.gitRepository }}"
          region: ${{ parameters.region }}
          source: ${{ parameters.environment.split(' ')[0].toLowerCase() }}
          target: ${{ parameters.environment.split(' ')[2].toLowerCase() }}
          projectName: ${{ parameters.projectName }}
          businessOwnerName: ${{ parameters.businessOwnerName }}
          businessOwnerEmail: ${{ parameters.businessOwnerEmail }}
          performS3Migration: ${{ parameters.performS3Migration }}
          migrationType: ${{ parameters.migrationType }}
          selectiveAssets: ${{ parameters.selectiveAssets }}

        apikey: ${{ parameters.token }}
