apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: servicenow-ticket-form
  title: ServiceNow Ticket Request
  description: Trigger a Harness pipeline with ServiceNow integration
  tags:
    - servicenow
    - harness
spec:
  owner: dev-team
  type: service

  parameters:
    - title: Request Info
      required:
        - requester
        - changeType
        - description
        - token
      properties:
        requester:
          type: string
          title: Requester Name
          description: Name of the person requesting the change
        changeType:
          type: string
          title: Change Type
          enum:
            - Standard
            - Normal
            - Emergency
          description: Type of change request
        description:
          type: string
          title: Description of the Change
          description: Provide a short description of the requested change
        token:
          title: Harness API Key
          type: string
          ui:widget: password
          description: API key to authenticate with Harness

  steps:
    - id: triggerPipeline
      name: Trigger Harness Pipeline
      action: harness:triggerPipeline
      input:
        org: default
        project: my-project
        pipeline: servicenow-pipeline
        apikey: ${{ parameters.token }}
        inputSet:
          requester: ${{ parameters.requester }}
          changeType: ${{ parameters.changeType }}
          description: ${{ parameters.description }}

  output:
    links:
      - title: "View Pipeline in Harness"
        url: "https://app.harness.io/ng/account/<accountId>/cd/orgs/default/projects/my-project/pipelines/servicenow-pipeline"
